#!/usr/bin/env python
"""
Generate prospective ARIMA forecasts with season-based conformal prediction intervals.

This script:
1. Loads pre-computed residuals from retrospective ARIMA forecasts
2. Trains per-location ARIMA models using all available data
3. Issues prospective forecasts for horizons 1-4 from the last date
4. Uses week-proximity weighted residuals for conformal intervals

Residuals are loaded from files generated by generate_retro_arima.py.

Usage examples:
  - Auto-detect latest imputed file and output to default folder
      python src/generate_prosp_arima.py --auto-latest

  - Explicit file with residuals directory
      python src/generate_prosp_arima.py \
        --data-file data/imputed_sets/imputed_and_stitched_hosp_2025-09-13.csv \
        --residuals-dir forecasts/retrospective/arima \
        --output forecasts/prospective
"""

import os
import argparse
import warnings
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from pmdarima import auto_arima, ARIMA
from scipy import stats

# Utils
import sys
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'utils'))
from pipeline_utils import find_latest_imputed

warnings.filterwarnings("ignore")


CDC_QUANTILES = np.array([
    0.01, 0.025, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5,
    0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 0.975, 0.99
])

# Season definition (inclusive): Nov 1 to May 1
SEASON_START_MONTH = 11  # November
SEASON_START_DAY = 1
SEASON_END_MONTH = 5     # May
SEASON_END_DAY = 1

# Week proximity weighting: weight = exp(-WEEK_DECAY * |week_diff|)
WEEK_DECAY = 0.1

# Cap on log-space residuals to avoid extreme outliers skewing the distribution
RESIDUAL_CAP = 2.5

# Minimum residuals for conformal intervals
MIN_RESIDUALS_FOR_CONFORMAL = 4

# Residuals file name pattern
RESIDUALS_FILE_PATTERN = 'arima_residuals_h{horizon}.csv'


STATE_TO_FIPS = {
    'Alabama': '01', 'Alaska': '02', 'Arizona': '04', 'Arkansas': '05',
    'California': '06', 'Colorado': '08', 'Connecticut': '09', 'Delaware': '10',
    'District of Columbia': '11', 'Florida': '12', 'Georgia': '13', 'Hawaii': '15',
    'Idaho': '16', 'Illinois': '17', 'Indiana': '18', 'Iowa': '19',
    'Kansas': '20', 'Kentucky': '21', 'Louisiana': '22', 'Maine': '23',
    'Maryland': '24', 'Massachusetts': '25', 'Michigan': '26', 'Minnesota': '27',
    'Mississippi': '28', 'Missouri': '29', 'Montana': '30', 'Nebraska': '31',
    'Nevada': '32', 'New Hampshire': '33', 'New Jersey': '34', 'New Mexico': '35',
    'New York': '36', 'North Carolina': '37', 'North Dakota': '38', 'Ohio': '39',
    'Oklahoma': '40', 'Oregon': '41', 'Pennsylvania': '42', 'Puerto Rico': '72',
    'Rhode Island': '44', 'South Carolina': '45', 'South Dakota': '46', 'Tennessee': '47',
    'Texas': '48', 'Utah': '49', 'Vermont': '50', 'Virginia': '51',
    'Washington': '53', 'West Virginia': '54', 'Wisconsin': '55', 'Wyoming': '56',
    'US': 'US'
}


def is_in_flu_season(date: pd.Timestamp) -> bool:
    """Check if a date is within the flu season (Nov 1 - May 1)."""
    month, day = date.month, date.day
    if month >= SEASON_START_MONTH:
        return True
    if month < SEASON_END_MONTH:
        return True
    if month == SEASON_END_MONTH and day <= SEASON_END_DAY:
        return True
    return False


def get_flu_season_year(date: pd.Timestamp) -> int:
    """Get the flu season year for a date. Season 2024 = Nov 2024 - May 2025."""
    if date.month >= SEASON_START_MONTH:
        return date.year
    else:
        return date.year - 1


def get_week_of_season(date: pd.Timestamp) -> int:
    """Get the week number within the flu season (0 = first week of Nov)."""
    season_year = get_flu_season_year(date)
    season_start = pd.Timestamp(year=season_year, month=SEASON_START_MONTH, day=SEASON_START_DAY)
    days_since_start = (date - season_start).days
    if days_since_start < 0:
        days_since_start += 365
    return days_since_start // 7


def week_proximity_weight(current_week: int, residual_week: int) -> float:
    """Calculate weight based on week proximity within season."""
    week_diff = abs(current_week - residual_week)
    return np.exp(-WEEK_DECAY * week_diff)


def weighted_percentile(values, weights, quantiles):
    """Compute weighted percentiles using linear interpolation."""
    values = np.array(values)
    weights = np.array(weights)
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]
    cumsum = np.cumsum(weights)
    cdf = cumsum / cumsum[-1]
    return np.interp(quantiles, cdf, values)


def load_wide(df_path: str) -> pd.DataFrame:
    df = pd.read_csv(df_path)
    df['date'] = pd.to_datetime(df['date'])
    wide = df.pivot(index='date', columns='location_name', values='total_hosp')
    wide = wide.asfreq('W-SAT')
    return wide


def determine_order(series: pd.Series) -> Tuple[int, int, int]:
    series = series.dropna()
    if len(series) < 20:
        return (1, 1, 1)
    try:
        model = auto_arima(series + 1,
                           start_p=0, max_p=8,
                           start_d=0, max_d=2,
                           start_q=0, max_q=8,
                           seasonal=False, stepwise=True, max_order=15,
                           n_fits=100, error_action='ignore', suppress_warnings=True,
                           trace=False)
        return model.order
    except Exception:
        return (1, 1, 1)


def fit_predict(series: pd.Series, order: Tuple[int, int, int], horizon: int) -> np.ndarray:
    series = series.dropna()
    if len(series) == 0:
        return np.full(horizon, np.nan)
    try:
        model = ARIMA(order=order, suppress_warnings=True)
        model.fit(series + 1)
        fc = model.predict(n_periods=horizon)
        return np.maximum(fc - 1, 0)
    except Exception:
        return np.array([series.iloc[-1]] * horizon)


def load_residuals(horizon: int, residuals_dir: str) -> pd.DataFrame:
    """Load pre-computed residuals for a given horizon."""
    residuals_file = os.path.join(residuals_dir, RESIDUALS_FILE_PATTERN.format(horizon=horizon))
    if not os.path.exists(residuals_file):
        print(f"  Warning: Residuals file not found: {residuals_file}")
        return pd.DataFrame()

    df = pd.read_csv(residuals_file)
    df['forecast_date'] = pd.to_datetime(df['forecast_date'])
    df['target_date'] = pd.to_datetime(df['target_date'])
    print(f"  Loaded {len(df)} residuals for horizon {horizon}")
    return df


def make_quantiles_weighted(point: float, residuals_df: pd.DataFrame, location: str,
                            current_week: int) -> np.ndarray:
    """Generate quantile forecasts using week-proximity weighted residuals."""
    # Filter residuals for this location
    loc_residuals = residuals_df[residuals_df['location'] == location]

    if len(loc_residuals) < MIN_RESIDUALS_FOR_CONFORMAL:
        # Fallback: use empirical spread
        std = max(abs(point) * 0.25, 5.0)
        return np.array([max(0.0, stats.norm.ppf(q, loc=point, scale=std)) for q in CDC_QUANTILES])

    # Apply week-proximity weighting
    weights = []
    residual_values = []

    for _, row in loc_residuals.iterrows():
        residual_week = int(row['week_of_season'])
        weight = week_proximity_weight(current_week, residual_week)
        weights.append(weight)
        # Cap residuals to avoid extreme outliers
        residual_log = np.clip(row['residual_log'], -RESIDUAL_CAP, RESIDUAL_CAP)
        residual_values.append(residual_log)

    # Compute weighted quantiles in log space
    mu_log = np.log1p(point)
    residual_quantiles = weighted_percentile(residual_values, weights, CDC_QUANTILES)
    q_log = mu_log + residual_quantiles

    # Transform back to original scale
    quantile_forecasts = np.array([max(0.0, np.expm1(val)) for val in q_log])

    return quantile_forecasts


def make_quantiles_fallback(point: float, errors: List[float]) -> np.ndarray:
    """Fallback quantile generation using simple percentiles (no weighting)."""
    if len(errors) < 10:
        std = max(abs(point) * 0.25, 5.0)
        return np.array([max(0.0, stats.norm.ppf(q, loc=point, scale=std)) for q in CDC_QUANTILES])
    err_q = np.percentile(errors, CDC_QUANTILES * 100)
    return np.maximum(point + err_q, 0.0)


def format_cdc(reference_date: pd.Timestamp, target_date: pd.Timestamp, fips: str, qvals: np.ndarray) -> List[Dict]:
    rows = []
    for qi, q in enumerate(CDC_QUANTILES):
        rows.append({
            'reference_date': reference_date.strftime('%Y-%m-%d'),
            'horizon': 0,  # prospective files use CDC-style single-target schema; horizon encoded in filename
            'target': 'wk inc flu hosp',
            'target_end_date': target_date.strftime('%Y-%m-%d'),
            'location': fips,
            'output_type': 'quantile',
            'output_type_id': q,
            'value': float(qvals[qi])
        })
    return rows


def main():
    ap = argparse.ArgumentParser(description='Generate prospective ARIMA forecasts (h=1..4)')
    ap.add_argument('--data-file', type=str, default=None, help='Path to imputed_and_stitched_hosp_*.csv')
    ap.add_argument('--auto-latest', action='store_true', help='Use latest imputed file automatically')
    ap.add_argument('--residuals-dir', type=str, default='forecasts/retrospective/arima',
                    help='Directory containing pre-computed residuals from retrospective ARIMA')
    ap.add_argument('--output', type=str, default='forecasts/prospective', help='Output directory')
    args = ap.parse_args()

    if args.auto_latest or not args.data_file:
        data_file = find_latest_imputed()
    else:
        data_file = args.data_file
    if not os.path.exists(data_file):
        raise FileNotFoundError(data_file)

    os.makedirs(args.output, exist_ok=True)

    print(f"{'='*80}")
    print("GENERATING PROSPECTIVE ARIMA FORECASTS")
    print(f"{'='*80}")
    print(f"Data file: {data_file}")
    print(f"Residuals dir: {args.residuals_dir}")
    print(f"Output: {args.output}")

    wide = load_wide(data_file)
    last_date = pd.to_datetime(wide.index.max())

    print(f"Last date in data: {last_date.date()}")

    # Check if we're in flu season
    if is_in_flu_season(last_date):
        current_week = get_week_of_season(last_date)
        print(f"Current week of flu season: {current_week}")
    else:
        current_week = 0
        print("Note: Not currently in flu season, using week 0 for weighting")

    # Load pre-computed residuals for each horizon
    residuals_by_horizon = {}
    use_weighted_conformal = True

    for h in range(1, 5):
        residuals_df = load_residuals(h, args.residuals_dir)
        if len(residuals_df) > 0:
            residuals_by_horizon[h] = residuals_df
        else:
            print(f"  Warning: No residuals for horizon {h}, will use fallback method")
            use_weighted_conformal = False

    # Determine best orders per location
    print("\nDetermining ARIMA orders...")
    best_orders = {}
    for loc in wide.columns:
        s = wide[loc].dropna()
        best_orders[loc] = determine_order(s)
        print(f"  {loc}: order={best_orders[loc]}")

    # Prospective forecasts from last_date
    print("\nGenerating prospective forecasts...")
    for h in range(1, 5):
        records = []
        residuals_df = residuals_by_horizon.get(h, pd.DataFrame())

        for loc in wide.columns:
            order = best_orders.get(loc, (1, 1, 1))
            preds = fit_predict(wide[loc], order, horizon=4)
            point = float(preds[h - 1]) if len(preds) >= h else np.nan

            if np.isnan(point):
                continue

            # Use weighted conformal if residuals available
            if len(residuals_df) > 0:
                qvals = make_quantiles_weighted(point, residuals_df, loc, current_week)
            else:
                qvals = make_quantiles_fallback(point, [])

            fips = STATE_TO_FIPS.get(loc, loc)
            target_date = last_date + pd.Timedelta(weeks=h)
            records.extend(format_cdc(last_date, target_date, fips, qvals))

        if records:
            out_df = pd.DataFrame(records)
            # Ensure column order
            cols = ['reference_date', 'horizon', 'target', 'target_end_date', 'location', 'output_type', 'output_type_id', 'value']
            out_df = out_df[cols]
            ts = last_date.strftime('%Y%m%d')
            out_path = os.path.join(args.output, f'ARIMA_h{h}_prospective_{ts}.csv')
            out_df.to_csv(out_path, index=False)
            print(f"Saved: {out_path} ({len(out_df)} rows)")

    print(f"\n{'='*80}")
    print("PROSPECTIVE ARIMA FORECASTING COMPLETE")
    print(f"{'='*80}")


if __name__ == '__main__':
    main()
