#!/usr/bin/env python
"""
Generate prospective ARIMA forecasts with plain conformal prediction intervals.

This script:
1. Loads pre-computed residuals from retrospective ARIMA forecasts
2. Trains per-location ARIMA models using all available data
3. Issues prospective forecasts for horizons 1-4 from the last date
4. Uses prior-season residuals for plain conformal intervals

Residuals are loaded from files generated by generate_retro_arima.py.

Usage examples:
  - Auto-detect latest imputed file and output to default folder
      python src/generate_prosp_arima.py --auto-latest

  - Explicit file with residuals directory
      python src/generate_prosp_arima.py \
        --data-file data/imputed_sets/imputed_and_stitched_hosp_2025-09-13.csv \
        --residuals-dir forecasts/retrospective/arima \
        --output forecasts/prospective
"""

import os
import argparse
import warnings
import pickle
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
from pmdarima import auto_arima, ARIMA
from scipy import stats

# Utils
import sys
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'utils'))
from pipeline_utils import find_latest_imputed

warnings.filterwarnings("ignore")


CDC_QUANTILES = np.array([
    0.01, 0.025, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5,
    0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 0.975, 0.99
])

# Season definition (inclusive): Nov 1 to May 1
SEASON_START_MONTH = 11  # November
SEASON_START_DAY = 1
SEASON_END_MONTH = 5     # May
SEASON_END_DAY = 1

# Cap on log-space residuals to avoid extreme outliers skewing the distribution
# Set to 1.6 to align with bounded-wide sigma max (0.8 * 1.96 ≈ 1.57)
RESIDUAL_CAP = 1.6

# Minimum residuals for conformal intervals
MIN_RESIDUALS_FOR_CONFORMAL = 4

# Residuals file name pattern
RESIDUALS_FILE_PATTERN = 'arima_residuals_h{horizon}.csv'

# Exogenous feature defaults
DEFAULT_DONOR_TOP_K = 5
DEFAULT_DONOR_MIN_OVERLAP = 30
SEASONAL_PERIOD_WEEKS = 52.1775


STATE_TO_FIPS = {
    'Alabama': '01', 'Alaska': '02', 'Arizona': '04', 'Arkansas': '05',
    'California': '06', 'Colorado': '08', 'Connecticut': '09', 'Delaware': '10',
    'District of Columbia': '11', 'Florida': '12', 'Georgia': '13', 'Hawaii': '15',
    'Idaho': '16', 'Illinois': '17', 'Indiana': '18', 'Iowa': '19',
    'Kansas': '20', 'Kentucky': '21', 'Louisiana': '22', 'Maine': '23',
    'Maryland': '24', 'Massachusetts': '25', 'Michigan': '26', 'Minnesota': '27',
    'Mississippi': '28', 'Missouri': '29', 'Montana': '30', 'Nebraska': '31',
    'Nevada': '32', 'New Hampshire': '33', 'New Jersey': '34', 'New Mexico': '35',
    'New York': '36', 'North Carolina': '37', 'North Dakota': '38', 'Ohio': '39',
    'Oklahoma': '40', 'Oregon': '41', 'Pennsylvania': '42', 'Puerto Rico': '72',
    'Rhode Island': '44', 'South Carolina': '45', 'South Dakota': '46', 'Tennessee': '47',
    'Texas': '48', 'Utah': '49', 'Vermont': '50', 'Virginia': '51',
    'Washington': '53', 'West Virginia': '54', 'Wisconsin': '55', 'Wyoming': '56',
    'US': 'US'
}


def build_seasonal_exog(index: pd.DatetimeIndex) -> pd.DataFrame:
    """Build deterministic seasonal exogenous features."""
    iso_week = index.isocalendar().week.to_numpy(dtype=float)
    angle = (2.0 * np.pi * iso_week) / SEASONAL_PERIOD_WEEKS

    exog = pd.DataFrame(index=index)
    exog['season_sin1'] = np.sin(angle)
    exog['season_cos1'] = np.cos(angle)
    exog['season_sin2'] = np.sin(2.0 * angle)
    exog['season_cos2'] = np.cos(2.0 * angle)
    exog['in_flu_season'] = np.array(
        [1.0 if is_in_flu_season(pd.Timestamp(d)) else 0.0 for d in index],
        dtype=float
    )
    return exog


def pairwise_corr_on_initial_window(
    series_a: pd.Series,
    series_b: pd.Series,
    min_overlap: int
) -> float:
    """Correlation in log-delta space on overlapping initial-window data."""
    a = np.log1p(series_a).diff()
    b = np.log1p(series_b).diff()
    aligned = pd.concat([a.rename('a'), b.rename('b')], axis=1).dropna()
    if len(aligned) < min_overlap:
        return np.nan
    return float(aligned['a'].corr(aligned['b']))


def select_donor_states(
    initial_wide: pd.DataFrame,
    top_k: int,
    min_overlap: int
) -> Dict[str, List[str]]:
    """Select top-k correlated donor states per location on initial training data only."""
    donor_map: Dict[str, List[str]] = {}
    locations = list(initial_wide.columns)

    for loc in locations:
        target = initial_wide[loc]
        scores: List[Tuple[str, float]] = []

        for donor in locations:
            if donor == loc:
                continue
            corr = pairwise_corr_on_initial_window(target, initial_wide[donor], min_overlap)
            if np.isnan(corr):
                continue
            scores.append((donor, corr))

        scores.sort(key=lambda x: x[1], reverse=True)
        donor_map[loc] = [name for name, _ in scores[:top_k]]

    return donor_map


def build_location_exog(
    wide_with_future: pd.DataFrame,
    location: str,
    donor_map: Dict[str, List[str]],
    donor_lag_weeks: int
) -> pd.DataFrame:
    """Build location-specific exogenous matrix using seasonal terms + lagged donors."""
    exog = build_seasonal_exog(wide_with_future.index)
    donors = donor_map.get(location, [])

    for i, donor in enumerate(donors, start=1):
        if donor not in wide_with_future.columns:
            continue
        exog[f'donor{i}_lag{donor_lag_weeks}'] = np.log1p(
            wide_with_future[donor].astype(float)
        ).shift(donor_lag_weeks)

    return exog


def prepare_train_inputs(
    y_series: pd.Series,
    exog_df: pd.DataFrame,
    min_rows: int = 20
) -> Tuple[Optional[pd.Series], Optional[np.ndarray]]:
    """Align target + exog and remove rows with NA."""
    merged = pd.concat([y_series.rename('y'), exog_df], axis=1).dropna()
    if len(merged) < min_rows:
        return None, None
    y = merged['y'].astype(float)
    X = merged.drop(columns=['y']).to_numpy(dtype=float)
    return y, X


def is_in_flu_season(date: pd.Timestamp) -> bool:
    """Check if a date is within the flu season (Nov 1 - May 1)."""
    month, day = date.month, date.day
    if month >= SEASON_START_MONTH:
        return True
    if month < SEASON_END_MONTH:
        return True
    if month == SEASON_END_MONTH and day <= SEASON_END_DAY:
        return True
    return False


def get_flu_season_year(date: pd.Timestamp) -> int:
    """Get the flu season year for a date. Season 2024 = Nov 2024 - May 2025."""
    if date.month >= SEASON_START_MONTH:
        return date.year
    else:
        return date.year - 1


def get_target_season_year(date: pd.Timestamp) -> int:
    """Return most recent COMPLETED flu season year for residuals."""
    current_season_year = get_flu_season_year(date)
    if is_in_flu_season(date):
        return current_season_year - 1
    return current_season_year


def get_week_of_season(date: pd.Timestamp) -> int:
    """Get the week number within the flu season (0 = first week of Nov)."""
    season_year = get_flu_season_year(date)
    season_start = pd.Timestamp(year=season_year, month=SEASON_START_MONTH, day=SEASON_START_DAY)
    days_since_start = (date - season_start).days
    if days_since_start < 0:
        days_since_start += 365
    return days_since_start // 7


def empirical_percentile(values, quantiles):
    """Compute empirical percentiles."""
    return np.quantile(np.asarray(values), quantiles)


def load_wide(df_path: str) -> pd.DataFrame:
    df = pd.read_csv(df_path)
    df['date'] = pd.to_datetime(df['date'])
    wide = df.pivot(index='date', columns='location_name', values='total_hosp')
    wide = wide.asfreq('W-SAT')
    return wide


def determine_order(series: pd.Series, exog_train: pd.DataFrame) -> Tuple[int, int, int]:
    y, X = prepare_train_inputs(series, exog_train, min_rows=20)
    if y is None or X is None:
        return (1, 1, 1)
    try:
        model = auto_arima(y + 1,
                           X=X,
                           start_p=0, max_p=8,
                           start_d=0, max_d=2,
                           start_q=0, max_q=8,
                           seasonal=False, stepwise=True, max_order=15,
                           n_fits=100, error_action='ignore', suppress_warnings=True,
                           trace=False)
        return model.order
    except Exception:
        return (1, 1, 1)


def fit_predict(
    series: pd.Series,
    exog_train: pd.DataFrame,
    exog_future: pd.DataFrame,
    order: Tuple[int, int, int],
    horizon: int
) -> np.ndarray:
    series = series.dropna()
    if len(series) == 0:
        return np.full(horizon, np.nan)
    try:
        y, X_train = prepare_train_inputs(series, exog_train, min_rows=20)
        if y is None or X_train is None:
            return np.array([series.iloc[-1]] * horizon)
        if exog_future.isnull().any().any():
            return np.array([series.iloc[-1]] * horizon)

        X_future = exog_future.to_numpy(dtype=float)
        model = ARIMA(order=order, suppress_warnings=True)
        model.fit(y + 1, X=X_train)
        fc = model.predict(n_periods=horizon, X=X_future)
        return np.maximum(fc - 1, 0)
    except Exception:
        return np.array([series.iloc[-1]] * horizon)


def load_residuals(horizon: int, residuals_dir: str) -> pd.DataFrame:
    """Load pre-computed residuals for a given horizon."""
    residuals_file = os.path.join(residuals_dir, RESIDUALS_FILE_PATTERN.format(horizon=horizon))
    if not os.path.exists(residuals_file):
        print(f"  Warning: Residuals file not found: {residuals_file}")
        return pd.DataFrame()

    df = pd.read_csv(residuals_file)
    df['forecast_date'] = pd.to_datetime(df['forecast_date'])
    df['target_date'] = pd.to_datetime(df['target_date'])
    print(f"  Loaded {len(df)} residuals for horizon {horizon}")
    return df


def make_quantiles_plain_conformal(point: float, residuals_df: pd.DataFrame, location: str) -> np.ndarray:
    """Generate quantile forecasts from prior-season residuals without median shifting."""
    # Filter residuals for this location
    loc_residuals = residuals_df[residuals_df['location'] == location]

    if len(loc_residuals) < MIN_RESIDUALS_FOR_CONFORMAL:
        # Fallback: use empirical spread
        std = max(abs(point) * 0.25, 5.0)
        return np.array([max(0.0, stats.norm.ppf(q, loc=point, scale=std)) for q in CDC_QUANTILES])

    residual_values = np.clip(loc_residuals['residual_log'].to_numpy(), -RESIDUAL_CAP, RESIDUAL_CAP)
    residual_values_centered = residual_values - np.median(residual_values)

    # Compute empirical conformal quantiles in log space; centering avoids residual-driven debiasing
    mu_log = np.log1p(point)
    residual_quantiles = empirical_percentile(residual_values_centered, CDC_QUANTILES)
    q_log = mu_log + residual_quantiles

    # Transform back to original scale
    quantile_forecasts = np.array([max(0.0, np.expm1(val)) for val in q_log])
    # Keep the median on the model point forecast (no de-biasing).
    quantile_forecasts[np.where(CDC_QUANTILES == 0.5)[0][0]] = max(0.0, point)

    return quantile_forecasts


def make_quantiles_fallback(point: float, errors: List[float]) -> np.ndarray:
    """Fallback quantile generation using simple percentiles (no weighting)."""
    if len(errors) < 10:
        std = max(abs(point) * 0.25, 5.0)
        return np.array([max(0.0, stats.norm.ppf(q, loc=point, scale=std)) for q in CDC_QUANTILES])
    err_q = np.percentile(errors, CDC_QUANTILES * 100)
    return np.maximum(point + err_q, 0.0)


def format_cdc(reference_date: pd.Timestamp, target_date: pd.Timestamp, fips: str, qvals: np.ndarray) -> List[Dict]:
    rows = []
    for qi, q in enumerate(CDC_QUANTILES):
        rows.append({
            'reference_date': reference_date.strftime('%Y-%m-%d'),
            'horizon': 0,  # prospective files use CDC-style single-target schema; horizon encoded in filename
            'target': 'wk inc flu hosp',
            'target_end_date': target_date.strftime('%Y-%m-%d'),
            'location': fips,
            'output_type': 'quantile',
            'output_type_id': q,
            'value': float(qvals[qi])
        })
    return rows


def load_model_info(model_info_file: str) -> Dict:
    """Load retrospective ARIMA model metadata if available."""
    if not os.path.exists(model_info_file):
        return {}
    try:
        with open(model_info_file, 'rb') as f:
            info = pickle.load(f)
        if isinstance(info, dict):
            return info
    except Exception:
        pass
    return {}


def normalize_order(order_obj) -> Tuple[int, int, int]:
    """Normalize order from metadata to a valid ARIMA order tuple."""
    try:
        if isinstance(order_obj, (list, tuple)) and len(order_obj) == 3:
            return tuple(int(x) for x in order_obj)
    except Exception:
        pass
    return (1, 1, 1)


def main():
    ap = argparse.ArgumentParser(description='Generate prospective ARIMA forecasts (h=1..4)')
    ap.add_argument('--data-file', type=str, default=None, help='Path to imputed_and_stitched_hosp_*.csv')
    ap.add_argument('--auto-latest', action='store_true', help='Use latest imputed file automatically')
    ap.add_argument('--residuals-dir', type=str, default='forecasts/retrospective/arima',
                    help='Directory containing pre-computed residuals from retrospective ARIMA')
    ap.add_argument('--output', type=str, default='forecasts/prospective', help='Output directory')
    ap.add_argument('--model-info-file', type=str, default=None,
                    help='Optional path to retrospective model_info.pkl (default: <residuals-dir>/model_info.pkl)')
    ap.add_argument('--donor-top-k', type=int, default=DEFAULT_DONOR_TOP_K,
                    help='Number of donor states to include as exogenous features')
    ap.add_argument('--donor-min-overlap', type=int, default=DEFAULT_DONOR_MIN_OVERLAP,
                    help='Minimum overlapping weeks for donor-correlation calculation')
    ap.add_argument('--donor-lag-weeks', type=int, default=None,
                    help='Lag (weeks) for donor exogenous features; default from model_info or 4')
    args = ap.parse_args()

    if args.auto_latest or not args.data_file:
        data_file = find_latest_imputed()
    else:
        data_file = args.data_file
    if not os.path.exists(data_file):
        raise FileNotFoundError(data_file)

    os.makedirs(args.output, exist_ok=True)

    print(f"{'='*80}")
    print("GENERATING PROSPECTIVE ARIMA FORECASTS")
    print(f"{'='*80}")
    print(f"Data file: {data_file}")
    print(f"Residuals dir: {args.residuals_dir}")
    print(f"Output: {args.output}")

    wide = load_wide(data_file)
    last_date = pd.to_datetime(wide.index.max())

    print(f"Last date in data: {last_date.date()}")
    target_season_year = get_target_season_year(last_date)
    print(f"Using residuals from season year: {target_season_year}")

    model_info_file = args.model_info_file or os.path.join(args.residuals_dir, 'model_info.pkl')
    model_info = load_model_info(model_info_file)
    if model_info:
        print(f"Loaded model metadata: {model_info_file}")
    else:
        print(f"Model metadata not found or unreadable: {model_info_file}")

    # Load pre-computed residuals for each horizon
    residuals_by_horizon = {}

    for h in range(1, 5):
        residuals_df = load_residuals(h, args.residuals_dir)
        if len(residuals_df) > 0:
            if 'season_year' in residuals_df.columns:
                residuals_df = residuals_df[residuals_df['season_year'] == target_season_year]
            else:
                print(f"  Warning: residuals missing season_year for horizon {h}, no season filter applied")
            residuals_by_horizon[h] = residuals_df
        else:
            print(f"  Warning: No residuals for horizon {h}, will use fallback method")

    # Donor selection: reuse retrospective donor map if available, else compute from initial half-window
    donor_lag_weeks = args.donor_lag_weeks
    if donor_lag_weeks is None:
        donor_lag_weeks = int(model_info.get('donor_lag_weeks', 4))

    donor_map = model_info.get('donor_map', {}) if isinstance(model_info.get('donor_map', {}), dict) else {}
    if donor_map:
        print(f"Using donor map from model metadata (locations={len(donor_map)})")
    else:
        split_point = max(20, len(wide) // 2)
        initial_wide = wide.iloc[:split_point]
        donor_map = select_donor_states(
            initial_wide,
            top_k=args.donor_top_k,
            min_overlap=args.donor_min_overlap
        )
        print(
            "Computed donor map from initial training window: "
            f"top_k={args.donor_top_k}, min_overlap={args.donor_min_overlap}, "
            f"lag_weeks={donor_lag_weeks}"
        )

    # Build exogenous matrices per location on index extended into forecast horizon
    horizon = 4
    future_dates = pd.date_range(
        start=last_date + pd.Timedelta(weeks=1),
        periods=horizon,
        freq='W-SAT'
    )
    wide_with_future = wide.reindex(wide.index.union(future_dates))
    exog_cache: Dict[str, pd.DataFrame] = {}
    for loc in wide.columns:
        exog_cache[loc] = build_location_exog(
            wide_with_future=wide_with_future,
            location=loc,
            donor_map=donor_map,
            donor_lag_weeks=donor_lag_weeks
        )

    # Determine best orders per location: prefer retrospective fixed orders if available
    print("\nDetermining ARIMA orders...")
    best_orders = model_info.get('best_orders', {}) if isinstance(model_info.get('best_orders', {}), dict) else {}
    for loc in wide.columns:
        if loc in best_orders:
            best_orders[loc] = normalize_order(best_orders[loc])
            print(f"  {loc}: order={best_orders[loc]} (from metadata)")
            continue
        s = wide[loc].dropna()
        exog_train = exog_cache[loc].loc[s.index]
        best_orders[loc] = normalize_order(determine_order(s, exog_train))
        print(f"  {loc}: order={best_orders[loc]}")

    # Prospective forecasts from last_date
    print("\nGenerating prospective forecasts...")
    for h in range(1, 5):
        records = []
        residuals_df = residuals_by_horizon.get(h, pd.DataFrame())

        for loc in wide.columns:
            order = normalize_order(best_orders.get(loc, (1, 1, 1)))
            loc_series = wide[loc].dropna()
            loc_exog = exog_cache[loc]
            train_exog = loc_exog.loc[loc_series.index]
            fc_index = pd.date_range(
                start=last_date + pd.Timedelta(weeks=1),
                periods=4,
                freq='W-SAT'
            )
            future_exog = loc_exog.reindex(fc_index)
            preds = fit_predict(loc_series, train_exog, future_exog, order, horizon=4)
            point = float(preds[h - 1]) if len(preds) >= h else np.nan

            if np.isnan(point):
                continue

            # Use plain conformal if residuals available
            if len(residuals_df) > 0:
                qvals = make_quantiles_plain_conformal(point, residuals_df, loc)
            else:
                qvals = make_quantiles_fallback(point, [])

            fips = STATE_TO_FIPS.get(loc, loc)
            target_date = last_date + pd.Timedelta(weeks=h)
            records.extend(format_cdc(last_date, target_date, fips, qvals))

        if records:
            out_df = pd.DataFrame(records)
            # Ensure column order
            cols = ['reference_date', 'horizon', 'target', 'target_end_date', 'location', 'output_type', 'output_type_id', 'value']
            out_df = out_df[cols]
            ts = last_date.strftime('%Y%m%d')
            out_path = os.path.join(args.output, f'ARIMA_h{h}_prospective_{ts}.csv')
            out_df.to_csv(out_path, index=False)
            print(f"Saved: {out_path} ({len(out_df)} rows)")

    print(f"\n{'='*80}")
    print("PROSPECTIVE ARIMA FORECASTING COMPLETE")
    print(f"{'='*80}")


if __name__ == '__main__':
    main()
